project_id = "ownacpshdrkwsfwiheau"

[functions.generate-invoice-pdf]
verify_jwt = false

[functions.send-reservation-confirmed]
verify_jwt = false

[functions.mpesa-stk-initiate]
verify_jwt = false

[functions.mpesa-stk-callback]
verify_jwt = false
